name: Notify Telegram on Push

on:
  push:
    branches:
      - gh-pages

jobs:
  notify-telegram:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Send message to Telegram
      - name: Send message to Telegram
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          AUTHOR=$(git log -1 --pretty=format:'%an')
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d text="🚀 New commit pushed to *${{ github.repository }}*:\n\n*Author*: ${AUTHOR}\n*Message*: ${COMMIT_MESSAGE}\n\n🔗 [View commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})" \
          -d parse_mode="Markdown"